namespace ManageAitportApp.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class updateBaseFieldName : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Aircraft", "UpdatedById", c => c.Int());
            AddColumn("dbo.Aircraft", "DeletedById", c => c.Int());
            AddColumn("dbo.Airports", "UpdatedById", c => c.Int());
            AddColumn("dbo.Airports", "DeletedById", c => c.Int());
            AddColumn("dbo.AirTraffics", "DeletedById", c => c.Int());
            AddColumn("dbo.Employees", "UpdatedById", c => c.Int());
            AddColumn("dbo.Employees", "DeletedById", c => c.Int());
            AddColumn("dbo.Flights", "UpdatedById", c => c.Int());
            AddColumn("dbo.Flights", "DeletedById", c => c.Int());
            AddColumn("dbo.Gates", "UpdatedById", c => c.Int());
            AddColumn("dbo.Gates", "DeletedById", c => c.Int());
            AddColumn("dbo.Terminals", "UpdatedById", c => c.Int());
            AddColumn("dbo.Terminals", "DeletedById", c => c.Int());
            AddColumn("dbo.Baggages", "UpdatedById", c => c.Int());
            AddColumn("dbo.Baggages", "DeletedById", c => c.Int());
            AddColumn("dbo.Tickets", "UpdatedById", c => c.Int());
            AddColumn("dbo.Tickets", "DeletedById", c => c.Int());
            AddColumn("dbo.Passengers", "UpdatedById", c => c.Int());
            AddColumn("dbo.Passengers", "DeletedById", c => c.Int());
            AddColumn("dbo.CheckIns", "UpdatedById", c => c.Int());
            AddColumn("dbo.CheckIns", "DeletedById", c => c.Int());
            AddColumn("dbo.CrewAssignments", "UpdatedById", c => c.Int());
            AddColumn("dbo.CrewAssignments", "DeletedById", c => c.Int());
            AddColumn("dbo.Logs", "DeletedById", c => c.Int());
            AddColumn("dbo.Settings", "DeletedById", c => c.Int());
            CreateIndex("dbo.Aircraft", "UpdatedById");
            CreateIndex("dbo.Aircraft", "DeletedById");
            CreateIndex("dbo.Employees", "UpdatedById");
            CreateIndex("dbo.Employees", "DeletedById");
            CreateIndex("dbo.Airports", "UpdatedById");
            CreateIndex("dbo.Airports", "DeletedById");
            CreateIndex("dbo.AirTraffics", "DeletedById");
            CreateIndex("dbo.Flights", "UpdatedById");
            CreateIndex("dbo.Flights", "DeletedById");
            CreateIndex("dbo.Gates", "UpdatedById");
            CreateIndex("dbo.Gates", "DeletedById");
            CreateIndex("dbo.Terminals", "UpdatedById");
            CreateIndex("dbo.Terminals", "DeletedById");
            CreateIndex("dbo.Baggages", "UpdatedById");
            CreateIndex("dbo.Baggages", "DeletedById");
            CreateIndex("dbo.Tickets", "UpdatedById");
            CreateIndex("dbo.Tickets", "DeletedById");
            CreateIndex("dbo.Passengers", "UpdatedById");
            CreateIndex("dbo.Passengers", "DeletedById");
            CreateIndex("dbo.CheckIns", "UpdatedById");
            CreateIndex("dbo.CheckIns", "DeletedById");
            CreateIndex("dbo.CrewAssignments", "UpdatedById");
            CreateIndex("dbo.CrewAssignments", "DeletedById");
            CreateIndex("dbo.Logs", "DeletedById");
            CreateIndex("dbo.Settings", "DeletedById");
            AddForeignKey("dbo.Airports", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Airports", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Employees", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Employees", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Aircraft", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Aircraft", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.AirTraffics", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Flights", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Gates", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Terminals", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Terminals", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Gates", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Flights", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Baggages", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Tickets", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Passengers", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Passengers", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Tickets", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Baggages", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.CheckIns", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.CheckIns", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.CrewAssignments", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.CrewAssignments", "UpdatedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Logs", "DeletedById", "dbo.Employees", "Id");
            AddForeignKey("dbo.Settings", "DeletedById", "dbo.Employees", "Id");
            DropColumn("dbo.Aircraft", "UpdatedBy");
            DropColumn("dbo.Aircraft", "DeletedBy");
            DropColumn("dbo.Airports", "UpdatedBy");
            DropColumn("dbo.Airports", "DeletedBy");
            DropColumn("dbo.AirTraffics", "DeletedBy");
            DropColumn("dbo.Employees", "UpdatedBy");
            DropColumn("dbo.Employees", "DeletedBy");
            DropColumn("dbo.Flights", "UpdatedBy");
            DropColumn("dbo.Flights", "DeletedBy");
            DropColumn("dbo.Gates", "UpdatedBy");
            DropColumn("dbo.Gates", "DeletedBy");
            DropColumn("dbo.Terminals", "UpdatedBy");
            DropColumn("dbo.Terminals", "DeletedBy");
            DropColumn("dbo.Baggages", "UpdatedBy");
            DropColumn("dbo.Baggages", "DeletedBy");
            DropColumn("dbo.Tickets", "UpdatedBy");
            DropColumn("dbo.Tickets", "DeletedBy");
            DropColumn("dbo.Passengers", "UpdatedBy");
            DropColumn("dbo.Passengers", "DeletedBy");
            DropColumn("dbo.CheckIns", "UpdatedBy");
            DropColumn("dbo.CheckIns", "DeletedBy");
            DropColumn("dbo.CrewAssignments", "UpdatedBy");
            DropColumn("dbo.CrewAssignments", "DeletedBy");
            DropColumn("dbo.Logs", "DeletedBy");
            DropColumn("dbo.Settings", "DeletedBy");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Settings", "DeletedBy", c => c.Int());
            AddColumn("dbo.Logs", "DeletedBy", c => c.Int());
            AddColumn("dbo.CrewAssignments", "DeletedBy", c => c.Int());
            AddColumn("dbo.CrewAssignments", "UpdatedBy", c => c.Int());
            AddColumn("dbo.CheckIns", "DeletedBy", c => c.Int());
            AddColumn("dbo.CheckIns", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Passengers", "DeletedBy", c => c.Int());
            AddColumn("dbo.Passengers", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Tickets", "DeletedBy", c => c.Int());
            AddColumn("dbo.Tickets", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Baggages", "DeletedBy", c => c.Int());
            AddColumn("dbo.Baggages", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Terminals", "DeletedBy", c => c.Int());
            AddColumn("dbo.Terminals", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Gates", "DeletedBy", c => c.Int());
            AddColumn("dbo.Gates", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Flights", "DeletedBy", c => c.Int());
            AddColumn("dbo.Flights", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Employees", "DeletedBy", c => c.Int());
            AddColumn("dbo.Employees", "UpdatedBy", c => c.Int());
            AddColumn("dbo.AirTraffics", "DeletedBy", c => c.Int());
            AddColumn("dbo.Airports", "DeletedBy", c => c.Int());
            AddColumn("dbo.Airports", "UpdatedBy", c => c.Int());
            AddColumn("dbo.Aircraft", "DeletedBy", c => c.Int());
            AddColumn("dbo.Aircraft", "UpdatedBy", c => c.Int());
            DropForeignKey("dbo.Settings", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Logs", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.CrewAssignments", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.CrewAssignments", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.CheckIns", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.CheckIns", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Baggages", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Tickets", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Passengers", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Passengers", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Tickets", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Baggages", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Flights", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Gates", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Terminals", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Terminals", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Gates", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Flights", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.AirTraffics", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Aircraft", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Aircraft", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Employees", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Employees", "DeletedById", "dbo.Employees");
            DropForeignKey("dbo.Airports", "UpdatedById", "dbo.Employees");
            DropForeignKey("dbo.Airports", "DeletedById", "dbo.Employees");
            DropIndex("dbo.Settings", new[] { "DeletedById" });
            DropIndex("dbo.Logs", new[] { "DeletedById" });
            DropIndex("dbo.CrewAssignments", new[] { "DeletedById" });
            DropIndex("dbo.CrewAssignments", new[] { "UpdatedById" });
            DropIndex("dbo.CheckIns", new[] { "DeletedById" });
            DropIndex("dbo.CheckIns", new[] { "UpdatedById" });
            DropIndex("dbo.Passengers", new[] { "DeletedById" });
            DropIndex("dbo.Passengers", new[] { "UpdatedById" });
            DropIndex("dbo.Tickets", new[] { "DeletedById" });
            DropIndex("dbo.Tickets", new[] { "UpdatedById" });
            DropIndex("dbo.Baggages", new[] { "DeletedById" });
            DropIndex("dbo.Baggages", new[] { "UpdatedById" });
            DropIndex("dbo.Terminals", new[] { "DeletedById" });
            DropIndex("dbo.Terminals", new[] { "UpdatedById" });
            DropIndex("dbo.Gates", new[] { "DeletedById" });
            DropIndex("dbo.Gates", new[] { "UpdatedById" });
            DropIndex("dbo.Flights", new[] { "DeletedById" });
            DropIndex("dbo.Flights", new[] { "UpdatedById" });
            DropIndex("dbo.AirTraffics", new[] { "DeletedById" });
            DropIndex("dbo.Airports", new[] { "DeletedById" });
            DropIndex("dbo.Airports", new[] { "UpdatedById" });
            DropIndex("dbo.Employees", new[] { "DeletedById" });
            DropIndex("dbo.Employees", new[] { "UpdatedById" });
            DropIndex("dbo.Aircraft", new[] { "DeletedById" });
            DropIndex("dbo.Aircraft", new[] { "UpdatedById" });
            DropColumn("dbo.Settings", "DeletedById");
            DropColumn("dbo.Logs", "DeletedById");
            DropColumn("dbo.CrewAssignments", "DeletedById");
            DropColumn("dbo.CrewAssignments", "UpdatedById");
            DropColumn("dbo.CheckIns", "DeletedById");
            DropColumn("dbo.CheckIns", "UpdatedById");
            DropColumn("dbo.Passengers", "DeletedById");
            DropColumn("dbo.Passengers", "UpdatedById");
            DropColumn("dbo.Tickets", "DeletedById");
            DropColumn("dbo.Tickets", "UpdatedById");
            DropColumn("dbo.Baggages", "DeletedById");
            DropColumn("dbo.Baggages", "UpdatedById");
            DropColumn("dbo.Terminals", "DeletedById");
            DropColumn("dbo.Terminals", "UpdatedById");
            DropColumn("dbo.Gates", "DeletedById");
            DropColumn("dbo.Gates", "UpdatedById");
            DropColumn("dbo.Flights", "DeletedById");
            DropColumn("dbo.Flights", "UpdatedById");
            DropColumn("dbo.Employees", "DeletedById");
            DropColumn("dbo.Employees", "UpdatedById");
            DropColumn("dbo.AirTraffics", "DeletedById");
            DropColumn("dbo.Airports", "DeletedById");
            DropColumn("dbo.Airports", "UpdatedById");
            DropColumn("dbo.Aircraft", "DeletedById");
            DropColumn("dbo.Aircraft", "UpdatedById");
        }
    }
}
